Update ssh.yml

diff --git a/.github/workflows/ssh.yml b/.github/workflows/ssh.yml
--- a/.github/workflows/ssh.yml
+++ b/.github/workflows/ssh.yml
@@ -69,7 +69,8 @@ jobs:
           bit remote
       - name: Bit import
         run: |
-          bit -v && bit import
+          bit -v
+          bit import || echo "Error on import"
       - name: Bit export
         run: |
           bit add src/components/*
