Update ssh.yml

diff --git a/.github/workflows/ssh.yml b/.github/workflows/ssh.yml
--- a/.github/workflows/ssh.yml
+++ b/.github/workflows/ssh.yml
@@ -60,7 +60,7 @@ jobs:
           bit config
       - name: Bit init
         run: |
-          bit init --standalone || echo "Error on init"
+          bit init || echo "Error on init"
       - name: Bit remote
         run: |
           bit remote add ssh://bit@ec2-54-80-100-75.compute-1.amazonaws.com:/opt/bit/${{ github.event.repository.name }}
